language: java

addons:
  sonarcloud:
    organization: "martlevemart-github"
    apt:
      update: true
      sources:
        - sourceline: "deb https://dl.bintray.com/gauge/gauge-deb stable main"
          key_url: "http://ha.pool.sks-keyservers.net/pks/lookup?search=0x023EDB0B&op=get&options=mr"
      packages:
        - gauge

sudo: true

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=martLeveMart_rename


    8b37110e0c81d5af51e64485acbcd5ee5c66b2fe